### ISSUE TITLE
Contract generation app

### ISSUE THREAD

**Issue by Xmaster6y** [clementine-per/ronrhone#13]
## User story
Isolate the contract generation in a Django app.

## Acceptance Criterion

* Code documented and typed
* The app is totally integrated
* The views, models, URLs, etc.,  are isolated

## Tasks

- [ ] Create the subapp
- [ ] Create the models
- [ ] Create the views
- [ ] Create the URLs
- [ ] Write unitary tests
